name: digia_inspector_core
description: Core debugging interfaces and contracts for Digia applications.
version: 0.0.1
homepage: https://www.digia.tech
repository: https://github.com/Digia-Technology-Private-Limited/digia_inspector_core
issue_tracker: https://github.com/Digia-Technology-Private-Limited/digia_inspector_core/issues
documentation: https://docs.digia.tech
topics:
  [debugging, logging, monitoring, networking, observability, digia, inspector]
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0
